# This file was generated by GoReleaser. DO NOT EDIT.
cask "goto-ssh-manager" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "5cc96438133165ff296810e71bf06cd3a385a686fff0bd05d80f4072cc3b2de2"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c0a9812d732c47af73511e4d76091e6d192c7776a7665b925c5f2ce1189b233"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1dd479db6717216faef0996616aa16554c74a5cdaaeb0f197ab661fb18a02dd6"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4254ad7ca190b9550b3a7eb46f04a7f915762ce2fef09d63abef76cddd13c6e2"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "goto-ssh-manager"
  desc "TUI SSH manager for organizing and quickly accessing SSH servers, with support for structured host lists, search, and interactive navigation."
  homepage "https://github.com/grafviktor/goto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gg"]
    end
  end

  # No zap stanza required

end
