# This file was generated by GoReleaser. DO NOT EDIT.
cask "goto-ssh-manager" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "9eba902f982d7849fa67df55e1b2ee6b9db7998faf7821fa30acd84f926af2c7"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4f028e09ee6974eb311a46c4da4b440040492463b4c078e27b82c68e92fa150"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b83bf5e4208becfa2c46697210e57d05394780049c55c7a6f6e9d16f20d79b5"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2abf4bc4916995112dcc5bb1a55a431083e21736403a819669b9793bb30d504"
      url "https://github.com/grafviktor/goto/releases/download/v#{version}/goto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "goto-ssh-manager"
  desc "TUI SSH manager for organizing and quickly accessing SSH servers, with support for structured host lists, search, and interactive navigation."
  homepage "https://github.com/grafviktor/goto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gg"]
    end
  end

  # No zap stanza required

end
